FROM node:22-alpine AS frontend-builder

WORKDIR /frontend

COPY frontend/. .

RUN sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirrors.tuna.tsinghua.edu.cn/alpine#g' /etc/apk/repositories && \
    apk add pnpm && \
    npm config set registry https://registry.npmmirror.com && \
    pnpm i && \
    pnpm run build:prod

FROM nginx:1.29-alpine

COPY --from=frontend-builder /frontend/dist /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/proxy_params /etc/nginx/proxy_params

EXPOSE 80

ENV TZ="Asia/Shanghai"

CMD ["nginx", "-g", "daemon off;"]